const m = @import("math.zig");

pub const Subproject = struct {
    name: []const u8,
    description: []const u8,
    images: []const []const u8,
};

pub const Portfolio = struct {
    title: []const u8,
    uri: []const u8,
    cover: []const u8,
    landing: []const u8,
    sticker: []const u8,
    colorUi: m.Vec4,
    colorSticker: m.Vec4,
    subprojects: []const Subproject,
};

pub const PORTFOLIO_LIST = [_]Portfolio {
    .{
        .title = "HALO",
        .uri = "/halo",
        .cover = "/images/HALO/attachbeam2/5.png",
        .landing = "/images/HALO/landing.png",
        .sticker = "/images/HALO/sticker-main.png",
        .colorUi = m.Vec4.init(0.0, 220.0 / 255.0, 164.0 / 255.0, 1.0),
        .colorSticker = m.Vec4.init(0.0, 220.0 / 255.0, 164.0 / 255.0, 1.0),
        .subprojects = &[_]Subproject {
            .{
                .name = "ATTACH BEAM",
                .description = "By attaching a tether to an opponent, the player is able to deliver a series of devastating pulses to further damage their enemy.",
                .images = &[_][]const u8{
                    "/images/HALO/attachbeam1/1.png",
                    "/images/HALO/attachbeam1/2.png",
                    "/images/HALO/attachbeam1/3.png",
                    "/images/HALO/attachbeam1/4.png",
                    "/images/HALO/attachbeam1/5.png",
                    "/images/HALO/attachbeam1/6.png",
                    "/images/HALO/attachbeam1/7.png",
                    "/images/HALO/attachbeam1/8.png",
                    "/images/HALO/attachbeam1/9.png",
                    "/images/HALO/attachbeam1/10.png",
                    "/images/HALO/attachbeam1/11.png",
                    "/images/HALO/attachbeam1/12.png",
                },
            },
            .{
                .name = "ATTACH BEAM II",
                .description = "Anyone who has played Halo knows that there's a lot of vehicular combat. Using the Attach Beam, a player connects a tether to their opponent's vehicle. Once connected, a player is able to deliver a series of pulses to destroy their enemy's vehicle.",
                .images = &[_][]const u8{
                    "/images/HALO/attachbeam2/1.png",
                    "/images/HALO/attachbeam2/2.png",
                    "/images/HALO/attachbeam2/3.png",
                    "/images/HALO/attachbeam2/4.png",
                    "/images/HALO/attachbeam2/5.png",
                    "/images/HALO/attachbeam2/6.png",
                    "/images/HALO/attachbeam2/7.png",
                    "/images/HALO/attachbeam2/8.png",
                    "/images/HALO/attachbeam2/9.png",
                    "/images/HALO/attachbeam2/10.png",
                    "/images/HALO/attachbeam2/11.png",
                    "/images/HALO/attachbeam2/12.png",
                },
            },
            .{
                .name = "BISHOP BEAM",
                .description = "By attaching a tether to an opponent, the player is able to deliver a series of devastating pulses to further damage their enemy.",
                .images = &[_][]const u8{
                    "/images/HALO/bishopbeam/1.png",
                    "/images/HALO/bishopbeam/2.png",
                    "/images/HALO/bishopbeam/3.png",
                    "/images/HALO/bishopbeam/4.png",
                    "/images/HALO/bishopbeam/5.png",
                    "/images/HALO/bishopbeam/6.png",
                },
            },
            .{
                .name = "FORERUNNER",
                .description = "By attaching a tether to an opponent, the player is able to deliver a series of devastating pulses to further damage their enemy.",
                .images = &[_][]const u8{
                    "/images/HALO/Forerunner/1.png",
                    "/images/HALO/Forerunner/2.png",
                    "/images/HALO/Forerunner/3.png",
                    "/images/HALO/Forerunner/4.png",
                    "/images/HALO/Forerunner/5.png",
                    "/images/HALO/Forerunner/6.png",
                    "/images/HALO/Forerunner/7.png",
                    "/images/HALO/Forerunner/8.png",
                    "/images/HALO/Forerunner/9.png",
                },
            },
            .{
                .name = "FORERUNNER II",
                .description = "By attaching a tether to an opponent, the player is able to deliver a series of devastating pulses to further damage their enemy.",
                .images = &[_][]const u8{
                    "/images/HALO/Forerunner2/1.png",
                    "/images/HALO/Forerunner2/2.png",
                    "/images/HALO/Forerunner2/3.png",
                    "/images/HALO/Forerunner2/4.png",
                    "/images/HALO/Forerunner2/5.png",
                    "/images/HALO/Forerunner2/6.png",
                },
            },
            .{
                .name = "GRAPPLE ARMOR",
                .description = "By attaching a tether to an opponent, the player is able to deliver a series of devastating pulses to further damage their enemy.",
                .images = &[_][]const u8{
                    "/images/HALO/GrappleArmor/1.png",
                    "/images/HALO/GrappleArmor/2.png",
                    "/images/HALO/GrappleArmor/3.png",
                    "/images/HALO/GrappleArmor/4.png",
                    "/images/HALO/GrappleArmor/5.png",
                    "/images/HALO/GrappleArmor/6.png",
                },
            },
            .{
                .name = "GRAPPLE BEAM",
                .description = "By attaching a tether to an opponent, the player is able to deliver a series of devastating pulses to further damage their enemy.",
                .images = &[_][]const u8{
                    "/images/HALO/GrappleBeam/1.png",
                    "/images/HALO/GrappleBeam/2.png",
                    "/images/HALO/GrappleBeam/3.png",
                    "/images/HALO/GrappleBeam/4.png",
                    "/images/HALO/GrappleBeam/5.png",
                    "/images/HALO/GrappleBeam/6.png",
                    "/images/HALO/GrappleBeam/7.png",
                    "/images/HALO/GrappleBeam/8.png",
                    "/images/HALO/GrappleBeam/9.png",
                    "/images/HALO/GrappleBeam/10.png",
                    "/images/HALO/GrappleBeam/11.png",
                },
            },
            .{
                .name = "MORTAR",
                .description = "By attaching a tether to an opponent, the player is able to deliver a series of devastating pulses to further damage their enemy.",
                .images = &[_][]const u8{
                    "/images/HALO/Mortar/1.png",
                    "/images/HALO/Mortar/2.png",
                    "/images/HALO/Mortar/3.png",
                    "/images/HALO/Mortar/4.png",
                    "/images/HALO/Mortar/5.png",
                    "/images/HALO/Mortar/6.png",
                    "/images/HALO/Mortar/7.png",
                    "/images/HALO/Mortar/8.png",
                },
            },
            .{
                .name = "PELICAN",
                .description = "By attaching a tether to an opponent, the player is able to deliver a series of devastating pulses to further damage their enemy.",
                .images = &[_][]const u8{
                    "/images/HALO/Pelican/1.png",
                    "/images/HALO/Pelican/2.png",
                    "/images/HALO/Pelican/3.png",
                    "/images/HALO/Pelican/4.png",
                    "/images/HALO/Pelican/5.png",
                    "/images/HALO/Pelican/6.png",
                    "/images/HALO/Pelican/7.png",
                    "/images/HALO/Pelican/8.png",
                    "/images/HALO/Pelican/9.png",
                    "/images/HALO/Pelican/10.png",
                    "/images/HALO/Pelican/11.png",
                },
            },
        },
    },
    .{
        .title = "Marvel: Contest of Champions",
        .uri = "/marvel-contest-of-champions",
        .cover = "/images/marvel/all/Mad_Titan_0025_26.png",
        .landing = "/images/HALO/landing.png",
        .sticker = "/images/marvel/sticker-main.png",
        .colorUi = m.Vec4.init(165.0 / 255.0, 56.0 / 255.0, 1.0, 1.0),
        .colorSticker = m.Vec4.init(165.0 / 255.0, 56.0 / 255.0, 1.0, 1.0),
        .subprojects = &[_]Subproject {
            .{
                .name = " ",
                .description = "By attaching a tether to an opponent, the player is able to deliver a series of devastating pulses to further damage their enemy.",
                .images = &[_][]const u8{
                    "/images/marvel/all/Mad_Titan_0000_01.png",
                    "/images/marvel/all/Mad_Titan_0001_02.png",
                    "/images/marvel/all/Mad_Titan_0002_03.png",
                    "/images/marvel/all/Mad_Titan_0003_04.png",
                    "/images/marvel/all/Mad_Titan_0004_05.png",
                    "/images/marvel/all/Mad_Titan_0005_06.png",
                    "/images/marvel/all/Mad_Titan_0006_07.png",
                    "/images/marvel/all/Mad_Titan_0007_08.png",
                    "/images/marvel/all/Mad_Titan_0008_09.png",
                    "/images/marvel/all/Mad_Titan_0009_10.png",
                    "/images/marvel/all/Mad_Titan_0010_11.png",
                    "/images/marvel/all/Mad_Titan_0011_12.png",
                    "/images/marvel/all/Mad_Titan_0012_13.png",
                    "/images/marvel/all/Mad_Titan_0013_14.png",
                    "/images/marvel/all/Mad_Titan_0014_15.png",
                    "/images/marvel/all/Mad_Titan_0015_16.png",
                    "/images/marvel/all/Mad_Titan_0016_17.png",
                    "/images/marvel/all/Mad_Titan_0017_18.png",
                    "/images/marvel/all/Mad_Titan_0018_19.png",
                    "/images/marvel/all/Mad_Titan_0019_20.png",
                },
            },
        },
    },
};
