name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: kapricorn-media/github/.github/workflows/zig-release.yaml@main
    with:
      zig-version: 0.12.0-dev.2063+804cee3b9
      package-name: yorstory
      zig-build-command: server_package
      package-subdir: server
      releaseFlag: -Doptimize=ReleaseFast
